name: Python Code Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install coverage

    - name: Run tests with coverage
      run: coverage run -m pytest

    - name: Generate coverage report
      run: coverage report
